import { codeToShape } from "./Shape"
import { Belt } from "./simulator/Belt"
import { Cutter } from "./simulator/Cutter"
import { Generator } from "./simulator/Generator"
import { Rotator } from "./simulator/Rotator"
import { createColorProduct, createShapeProduct, Rotation } from "./simulator/utils"
import { SimulatorGraph } from "./simulatorGraph/SimulatorGraph"

function g2BeltRedundantSplit(): SimulatorGraph {
  const graph = new SimulatorGraph()

  graph.addNode(new Generator({ id: 'shx' }, createShapeProduct(codeToShape('CrRgSbWm'))))
  graph.addNode(new Belt({ id: 'A' }))
  graph.addNode(new Belt({ id: 'B' }))
  graph.addNode(new Belt({ id: 'C' }))
  graph.addNode(new Belt({ id: 'D' }))
  graph.addNode(new Belt({ id: 'E' }))
  graph.addNode(new Belt({ id: 'F' }))
  graph.addNode(new Belt({ id: 'G' }))
  graph.addNode(new Belt({ id: 'H' }))
  graph.addNode(new Belt({ id: 'I' }))
  graph.addNode(new Belt({ id: 'J' }))
  graph.addNode(new Belt({ id: 'K' }))
  graph.addNode(new Belt({ id: 'L' }))
  graph.addNode(new Belt({ id: 'M' }))
  graph.addNode(new Belt({ id: 'N' }))
  
  graph.addEdge('shx', 'A', 'shape')
  graph.addEdge('A', 'B', 'shape')
  graph.addEdge('B', 'C', 'shape')
  graph.addEdge('B', 'F', 'shape')
  graph.addEdge('C', 'D', 'shape')
  graph.addEdge('D', 'E', 'shape')
  graph.addEdge('F', 'G', 'shape')
  graph.addEdge('F', 'I', 'shape')
  graph.addEdge('G', 'H', 'shape')
  graph.addEdge('G', 'J', 'shape')
  graph.addEdge('H', 'K', 'shape')
  graph.addEdge('I', 'L', 'shape')
  graph.addEdge('J', 'M', 'shape')
  graph.addEdge('K', 'N', 'shape')
  graph.addEdge('L', 'D', 'shape')
  graph.addEdge('M', 'L', 'shape')
  graph.addEdge('N', 'M', 'shape')

  return graph
}

function g3BeltBalancer(): SimulatorGraph {
  const graph = new SimulatorGraph()

  graph.addNode(new Generator({ id: 'shx' }, createShapeProduct(codeToShape('CrRgSbWm'))))
  graph.addNode(new Generator({ id: 'shy' }, createShapeProduct(codeToShape('RbSyCrWy'))))
  graph.addNode(new Belt({ id: 'A' }))
  graph.addNode(new Belt({ id: 'B' }))
  graph.addNode(new Belt({ id: 'C' }))
  graph.addNode(new Belt({ id: 'D' }))
  graph.addNode(new Belt({ id: 'E' }))
  graph.addNode(new Belt({ id: 'F' }))
  graph.addNode(new Belt({ id: 'G' }))
  graph.addNode(new Belt({ id: 'H' }))
  graph.addNode(new Belt({ id: 'I' }))
  graph.addNode(new Belt({ id: 'J' }))
  
  graph.addEdge('shx', 'A', 'shape')
  graph.addEdge('shy', 'G', 'shape')
  graph.addEdge('A', 'B', 'shape')
  graph.addEdge('B', 'C', 'shape')
  graph.addEdge('B', 'D', 'shape')
  graph.addEdge('C', 'I', 'shape')
  graph.addEdge('D', 'E', 'shape')
  graph.addEdge('E', 'F', 'shape')
  graph.addEdge('G', 'H', 'shape')
  graph.addEdge('H', 'D', 'shape')
  graph.addEdge('H', 'I', 'shape')
  graph.addEdge('I', 'J', 'shape')

  return graph
}

function g4BeltMerge(): SimulatorGraph {
  const graph = new SimulatorGraph()

  graph.addNode(new Generator({ id: 'shx' }, createShapeProduct(codeToShape('CrRgSbWm'))))
  graph.addNode(new Generator({ id: 'shy' }, createShapeProduct(codeToShape('RbSyCrWy'))))
  graph.addNode(new Belt({ id: 'A' }))
  graph.addNode(new Belt({ id: 'B' }))
  graph.addNode(new Belt({ id: 'C' }))
  graph.addNode(new Belt({ id: 'D' }))
  graph.addNode(new Belt({ id: 'E' }))
  graph.addNode(new Belt({ id: 'F' }))
  graph.addNode(new Belt({ id: 'G' }))
  graph.addNode(new Belt({ id: 'H' }))
  graph.addNode(new Belt({ id: 'I' }))
  graph.addNode(new Belt({ id: 'J' }))
  graph.addNode(new Belt({ id: 'K' }))
  graph.addNode(new Belt({ id: 'L' }))
  graph.addNode(new Belt({ id: 'M' }))
  graph.addNode(new Belt({ id: 'N' }))
  
  graph.addEdge('shx', 'A', 'shape')
  graph.addEdge('shy', 'J', 'shape')
  graph.addEdge('A', 'B', 'shape')
  graph.addEdge('B', 'C', 'shape')
  graph.addEdge('B', 'F', 'shape')
  graph.addEdge('C', 'D', 'shape')
  graph.addEdge('D', 'E', 'shape')
  graph.addEdge('F', 'G', 'shape')
  graph.addEdge('G', 'H', 'shape')
  graph.addEdge('H', 'D', 'shape')
  graph.addEdge('I', 'E', 'shape')
  graph.addEdge('J', 'K', 'shape')
  graph.addEdge('K', 'F', 'shape')
  graph.addEdge('K', 'L', 'shape')
  graph.addEdge('L', 'M', 'shape')
  graph.addEdge('M', 'N', 'shape')
  graph.addEdge('N', 'I', 'shape')

  return graph
}

function g10TwoCuttersParallel(): SimulatorGraph {
  const graph = new SimulatorGraph()

  graph.addNode(new Generator({ id: 'shape-source' }, createShapeProduct(codeToShape('CrRgSbWm'))))
  graph.addNode(new Belt({ id: 'A' }))
  graph.addNode(new Belt({ id: 'B' }))
  graph.addNode(new Cutter({ id: 'C' }))
  graph.addNode(new Belt({ id: 'D' }))
  graph.addNode(new Belt({ id: 'E' }))
  graph.addNode(new Belt({ id: 'F' }))
  graph.addNode(new Belt({ id: 'G' }))
  // graph.addNode(new Belt({ id: 'H' }))
  graph.addNode(new Rotator({ id: 'I' }, Rotation.HalfTurn))
  graph.addNode(new Belt({ id: 'J' }))
  graph.addNode(new Belt({ id: 'K' }))
  graph.addNode(new Cutter({ id: 'L' }))
  graph.addNode(new Belt({ id: 'M' }))
  graph.addNode(new Belt({ id: 'N' }))
  graph.addNode(new Rotator({ id: 'O' }, Rotation.HalfTurn))
  graph.addNode(new Belt({ id: 'P' }))

  graph.addEdge('shape-source', 'A', 'shape')
  graph.addEdge('A', 'B', 'shape')
  graph.addEdge('B', 'C', 'shape')
  graph.addEdge('B', 'G', 'shape')
  graph.addEdge('C', 'D', 'shape', 0)
  graph.addEdge('C', 'I', 'shape', 1)
  graph.addEdge('D', 'E', 'shape')
  graph.addEdge('E', 'F', 'shape')
  graph.addEdge('G', 'K', 'shape')
  graph.addEdge('K', 'L', 'shape')
  graph.addEdge('I', 'J', 'shape')
  graph.addEdge('J', 'E', 'shape')
  graph.addEdge('L', 'M', 'shape', 0)
  graph.addEdge('L', 'O', 'shape', 1)
  graph.addEdge('M', 'N', 'shape')
  graph.addEdge('O', 'P', 'shape')
  graph.addEdge('P', 'N', 'shape')
  graph.addEdge('N', 'J', 'shape')

  return graph
}

function g14ExtraStackers(): SimulatorGraph {
  const graph = new SimulatorGraph()

  graph.addNode(new Generator({ id: 'shx' }, createShapeProduct(codeToShape('CrRgSbWm'))))
  graph.addNode(new Belt({ id: 'A' }))
  graph.addNode(new Belt({ id: 'B' }))
  graph.addNode(new Belt({ id: 'C' }))
  graph.addNode(new Belt({ id: 'D' }))
  graph.addNode(new Belt({ id: 'E' }))
  graph.addNode(new Belt({ id: 'F' }))
  graph.addNode(new Belt({ id: 'G' }))
  graph.addNode(new Belt({ id: 'H' }))
  graph.addNode(new Belt({ id: 'I' }))
  graph.addNode(new Belt({ id: 'J' }))
  graph.addNode(new Belt({ id: 'K' }))
  graph.addNode(new Belt({ id: 'L' }))
  graph.addNode(new Belt({ id: 'M' }))
  graph.addNode(new Belt({ id: 'N' }))
  graph.addNode(new Belt({ id: 'O' }))
  graph.addNode(new Belt({ id: 'P' }))
  graph.addNode(new Belt({ id: 'Q' }))
  graph.addNode(new Belt({ id: 'R' }))
  graph.addNode(new Belt({ id: 'S' }))
  graph.addNode(new Belt({ id: 'T' }))
  graph.addNode(new Belt({ id: 'U' }))
  
  graph.addEdge('shx', 'A', 'shape')
  graph.addEdge('A', 'B', 'shape')
  graph.addEdge('B', 'C', 'shape')
  graph.addEdge('B', 'J', 'shape', 1)
  graph.addEdge('C', 'K', 'shape')
  graph.addEdge('C', 'D', 'shape')
  graph.addEdge('D', 'L', 'shape', 1)
  graph.addEdge('D', 'E', 'shape')
  graph.addEdge('E', 'M', 'shape')
  graph.addEdge('E', 'F', 'shape')
  graph.addEdge('F', 'N', 'shape', 1)
  graph.addEdge('F', 'G', 'shape')
  graph.addEdge('G', 'O', 'shape')
  graph.addEdge('G', 'H', 'shape')
  graph.addEdge('H', 'P', 'shape', 1)
  graph.addEdge('H', 'I', 'shape')
  graph.addEdge('I', 'Q', 'shape')
  graph.addEdge('J', 'R', 'shape')
  graph.addEdge('K', 'J', 'shape', 2)
  graph.addEdge('L', 'S', 'shape')
  graph.addEdge('M', 'L', 'shape', 2)
  graph.addEdge('N', 'T', 'shape')
  graph.addEdge('O', 'N', 'shape', 2)
  graph.addEdge('P', 'U', 'shape')
  graph.addEdge('Q', 'P', 'shape', 2)
  
  return graph
}

function mixerAndPainters(): SimulatorGraph {
  const graph = new SimulatorGraph()

  graph.addNode(new Generator({ id: 'shx' }, createShapeProduct(codeToShape('CrRgSbWm'))))
  graph.addNode(new Generator({ id: 'col-r' }, createColorProduct('r', 1200)))
  graph.addNode(new Generator({ id: 'col-b' }, createColorProduct('b', 1200)))
  graph.addNode(new Belt({ id: 'A' }))
  graph.addNode(new Belt({ id: 'B' }))
  graph.addNode(new Belt({ id: 'C' }))
  graph.addNode(new Belt({ id: 'D' }))
  graph.addNode(new Belt({ id: 'E' }))
  graph.addNode(new Belt({ id: 'F' }))
  graph.addNode(new Belt({ id: 'G' }))
  graph.addNode(new Belt({ id: 'H' }))
  graph.addNode(new Belt({ id: 'I' }))
  graph.addNode(new Belt({ id: 'J' }))
  graph.addNode(new Belt({ id: 'K' }))
  // graph.addNode(new Belt({ id: 'L' }))
  graph.addNode(new Belt({ id: 'M' }))
  graph.addNode(new Belt({ id: 'N' }))
  graph.addNode(new Belt({ id: 'O' }))
  graph.addNode(new Belt({ id: 'P' }))
  graph.addNode(new Belt({ id: 'Q' }))
  graph.addNode(new Belt({ id: 'R' }))
  graph.addNode(new Belt({ id: 'S' }))
  graph.addNode(new Belt({ id: 'T' }))
  graph.addNode(new Belt({ id: 'U' }))
  graph.addNode(new Belt({ id: 'V' }))
  graph.addNode(new Belt({ id: 'W' }))
  graph.addNode(new Belt({ id: 'X' }))
  graph.addNode(new Belt({ id: 'Y' }))
  graph.addNode(new Belt({ id: 'Z' }))
  graph.addNode(new Belt({ id: 'AA' }))
  graph.addNode(new Belt({ id: 'AB' }))
  graph.addNode(new Belt({ id: 'AC' }))
  graph.addNode(new Belt({ id: 'AD' }))
  graph.addNode(new Belt({ id: 'AE' }))
  graph.addNode(new Belt({ id: 'AF' }))
  graph.addNode(new Belt({ id: 'AG' }))
  graph.addNode(new Belt({ id: 'AH' }))
  graph.addNode(new Belt({ id: 'AI' }))
  graph.addNode(new Belt({ id: 'AJ' }))
  graph.addNode(new Belt({ id: 'AK' }))
  graph.addNode(new Belt({ id: 'AL' }))
  graph.addNode(new Belt({ id: 'AM' }))
  graph.addNode(new Belt({ id: 'AN' }))
  graph.addNode(new Belt({ id: 'AO' }))
  graph.addNode(new Belt({ id: 'AP' }))
  graph.addNode(new Belt({ id: 'AQ' }))
  graph.addNode(new Belt({ id: 'AR' }))
  graph.addNode(new Belt({ id: 'AS' }))
  graph.addNode(new Belt({ id: 'AT' }))
  graph.addNode(new Belt({ id: 'AU' }))
  graph.addNode(new Belt({ id: 'AV' }))
  graph.addNode(new Belt({ id: 'AW' }))
  graph.addNode(new Belt({ id: 'AX' }))
  graph.addNode(new Belt({ id: 'AY' }))
  graph.addNode(new Belt({ id: 'AZ' }))
  graph.addNode(new Belt({ id: 'BA' }))
  graph.addNode(new Belt({ id: 'BB' }))
  graph.addNode(new Belt({ id: 'BC' }))
  graph.addNode(new Belt({ id: 'BD' }))
  graph.addNode(new Belt({ id: 'BE' }))
  graph.addNode(new Belt({ id: 'BF' }))
  graph.addNode(new Belt({ id: 'BG' }))
  graph.addNode(new Belt({ id: 'BH' }))
  
  graph.addEdge('col-r', 'A', 'color')
  graph.addEdge('col-b', 'G', 'color')
  graph.addEdge('shx', 'AM', 'shape')
  graph.addEdge('A', 'B', 'color')
  graph.addEdge('B', 'C', 'color')
  graph.addEdge('B', 'D', 'color')
  graph.addEdge('C', 'N', 'color')
  graph.addEdge('D', 'E', 'color')
  graph.addEdge('E', 'F', 'color')
  graph.addEdge('F', 'O', 'color')
  graph.addEdge('G', 'H', 'color')
  graph.addEdge('G', 'I', 'color')
  graph.addEdge('H', 'N', 'color')
  graph.addEdge('I', 'J', 'color')
  graph.addEdge('J', 'K', 'color')
  graph.addEdge('K', 'M', 'color')
  graph.addEdge('M', 'O', 'color')
  graph.addEdge('N', 'P', 'color')
  graph.addEdge('O', 'R', 'color')
  graph.addEdge('P', 'Q', 'color')
  graph.addEdge('Q', 'AA', 'color')
  graph.addEdge('R', 'Q', 'color')
  graph.addEdge('R', 'S', 'color')
  graph.addEdge('S', 'T', 'color')
  graph.addEdge('T', 'U', 'color')
  graph.addEdge('T', 'AB', 'color')
  graph.addEdge('U', 'V', 'color')
  graph.addEdge('V', 'W', 'color')
  graph.addEdge('W', 'AC', 'color')
  graph.addEdge('W', 'X', 'color')
  graph.addEdge('X', 'Y', 'color')
  graph.addEdge('Y', 'Z', 'color')
  graph.addEdge('Z', 'AD', 'color')
  graph.addEdge('AA', 'AE', 'color')
  graph.addEdge('AB', 'AF', 'color')
  graph.addEdge('AC', 'AG', 'color')
  graph.addEdge('AD', 'AH', 'color')
  graph.addEdge('AE', 'AI', 'color')
  graph.addEdge('AF', 'AJ', 'color')
  graph.addEdge('AG', 'AK', 'color')
  graph.addEdge('AH', 'AL', 'color')
  graph.addEdge('AI', 'AX', 'shape')
  graph.addEdge('AJ', 'BA', 'shape')
  graph.addEdge('AK', 'BD', 'shape')
  graph.addEdge('AL', 'BG', 'shape')
  graph.addEdge('AM', 'AN', 'shape')
  graph.addEdge('AN', 'AO', 'shape')
  graph.addEdge('AO', 'AP', 'shape')
  graph.addEdge('AP', 'AQ', 'shape')
  graph.addEdge('AQ', 'AR', 'shape')
  graph.addEdge('AQ', 'AT', 'shape')
  graph.addEdge('AQ', 'AK', 'shape')
  graph.addEdge('AR', 'AS', 'shape')
  graph.addEdge('AS', 'AL', 'shape')
  graph.addEdge('AT', 'AU', 'shape')
  graph.addEdge('AU', 'AS', 'shape')
  graph.addEdge('AU', 'AV', 'shape')
  graph.addEdge('AV', 'AW', 'shape')
  graph.addEdge('AW', 'AI', 'shape')
  graph.addEdge('AX', 'BH', 'shape')
  graph.addEdge('AY', 'AX', 'shape')
  graph.addEdge('AZ', 'AY', 'shape')
  graph.addEdge('BA', 'AZ', 'shape')
  graph.addEdge('BB', 'BA', 'shape')
  graph.addEdge('BC', 'BB', 'shape')
  graph.addEdge('BD', 'BC', 'shape')
  graph.addEdge('BE', 'BD', 'shape')
  graph.addEdge('BF', 'BE', 'shape')
  graph.addEdge('BG', 'BF', 'shape')
  
  return graph
}

export default {
  g2BeltRedundantSplit,
  g3BeltBalancer,
  g4BeltMerge,
  g10TwoCuttersParallel,
  g14ExtraStackers,
  mixerAndPainters,
}