import { codeToShape } from "./Shape"
import { Belt } from "./simulator/Belt"
import { ColorMixer } from "./simulator/ColorMixer"
import { Cutter } from "./simulator/Cutter"
import { Generator } from "./simulator/Generator"
import { Painter } from "./simulator/Painter"
import { Pipe } from "./simulator/Pipe"
import { Rotator } from "./simulator/Rotator"
import { Stacker } from "./simulator/Stacker"
import { Swapper } from "./simulator/Swapper"
import { Trash } from "./simulator/Trash"
import { createColorProduct, createShapeProduct, Rotation } from "./simulator/utils"
import { SimulatorGraph } from "./simulatorGraph/SimulatorGraph"

function swapperSameIO(): SimulatorGraph {
  const graph = new SimulatorGraph()

  graph.addNode(new Generator({ id: 'shx' }, createShapeProduct(codeToShape('CrRgSbWm'))))
  graph.addNode(new Generator({ id: 'shy' }, createShapeProduct(codeToShape('SbWmCrRg'))))
  graph.addNode(new Belt({ id: 'A' }))
  graph.addNode(new Belt({ id: 'B' }))
  graph.addNode(new Belt({ id: 'C' }))
  graph.addNode(new Belt({ id: 'D' }))
  graph.addNode(new Belt({ id: 'E' }))
  graph.addNode(new Belt({ id: 'F' }))
  graph.addNode(new Belt({ id: 'G' }))
  graph.addNode(new Belt({ id: 'H' }))
  graph.addNode(new Belt({ id: 'I' }))
  graph.addNode(new Belt({ id: 'J' }))
  graph.addNode(new Belt({ id: 'K' }))
  graph.addNode(new Belt({ id: 'L' }))
  graph.addNode(new Belt({ id: 'M' }))
  graph.addNode(new Belt({ id: 'N' }))
  graph.addNode(new Belt({ id: 'O' }))
  graph.addNode(new Belt({ id: 'P' }))
  graph.addNode(new Belt({ id: 'Q' }))
  graph.addNode(new Belt({ id: 'R' }))
  graph.addNode(new Belt({ id: 'S' }))
  graph.addNode(new Belt({ id: 'T' }))
  graph.addNode(new Belt({ id: 'U' }))
  graph.addNode(new Belt({ id: 'V' }))
  graph.addNode(new Belt({ id: 'W' }))
  graph.addNode(new Belt({ id: 'X' }))
  graph.addNode(new Swapper({ id: 'Y' }))
  graph.addNode(new Swapper({ id: 'Z' }))
  graph.addNode(new Swapper({ id: 'AA' }))
  graph.addNode(new Belt({ id: 'AB' }))
  graph.addNode(new Belt({ id: 'AC' }))
  graph.addNode(new Belt({ id: 'AD' }))
  graph.addNode(new Belt({ id: 'AE' }))
  graph.addNode(new Belt({ id: 'AF' }))
  graph.addNode(new Belt({ id: 'AG' }))
  graph.addNode(new Belt({ id: 'AH' }))
  graph.addNode(new Belt({ id: 'AI' }))
  graph.addNode(new Belt({ id: 'AJ' }))
  graph.addNode(new Belt({ id: 'AK' }))
  graph.addNode(new Belt({ id: 'AL' }))
  graph.addNode(new Belt({ id: 'AM' }))
  graph.addNode(new Belt({ id: 'AN' }))
  graph.addNode(new Belt({ id: 'AO' }))
  graph.addNode(new Belt({ id: 'AP' }))
  graph.addNode(new Belt({ id: 'AQ' }))
  graph.addNode(new Belt({ id: 'AR' }))
  graph.addNode(new Belt({ id: 'AS' }))
  graph.addNode(new Belt({ id: 'AT' }))
  graph.addNode(new Belt({ id: 'AU' }))
  graph.addNode(new Belt({ id: 'AV' }))
  graph.addNode(new Belt({ id: 'AW' }))
  graph.addNode(new Belt({ id: 'AX' }))
  graph.addNode(new Belt({ id: 'AY' }))
  graph.addNode(new Belt({ id: 'AZ' }))
  graph.addNode(new Trash({ id: 'endA' }))
  graph.addNode(new Trash({ id: 'endB' }))
  
  graph.addEdge('shx', 'A', 'shape')
  graph.addEdge('shy', 'B', 'shape')
  graph.addEdge('A', 'C', 'shape')
  graph.addEdge('B', 'D', 'shape')
  graph.addEdge('C', 'K', 'shape')
  graph.addEdge('D', 'E', 'shape')
  graph.addEdge('D', 'T', 'shape')
  graph.addEdge('E', 'F', 'shape')
  graph.addEdge('F', 'G', 'shape')
  graph.addEdge('G', 'H', 'shape')
  graph.addEdge('G', 'V', 'shape')
  graph.addEdge('H', 'I', 'shape')
  graph.addEdge('I', 'J', 'shape')
  graph.addEdge('J', 'R', 'shape')
  graph.addEdge('K', 'S', 'shape')
  graph.addEdge('K', 'L', 'shape')
  graph.addEdge('L', 'M', 'shape')
  graph.addEdge('M', 'N', 'shape')
  graph.addEdge('N', 'U', 'shape')
  graph.addEdge('N', 'O', 'shape')
  graph.addEdge('O', 'P', 'shape')
  graph.addEdge('P', 'Q', 'shape')
  graph.addEdge('Q', 'W', 'shape')
  graph.addEdge('R', 'X', 'shape')
  graph.addEdge('S', 'Y', 'shape', 0)
  graph.addEdge('T', 'Y', 'shape', 1)
  graph.addEdge('U', 'Z', 'shape', 0)
  graph.addEdge('V', 'Z', 'shape', 1)
  graph.addEdge('W', 'AA', 'shape' , 0)
  graph.addEdge('X', 'AA', 'shape' , 1)
  graph.addEdge('Y', 'AB', 'shape', undefined, 0)
  graph.addEdge('Y', 'AC', 'shape', undefined, 1)
  graph.addEdge('Z', 'AD', 'shape', undefined, 0)
  graph.addEdge('Z', 'AE', 'shape', undefined, 1)
  graph.addEdge('AA', 'AF', 'shape', undefined, 0)
  graph.addEdge('AA', 'AG', 'shape', undefined, 1)
  graph.addEdge('AB', 'AH', 'shape')
  graph.addEdge('AC', 'AI', 'shape')
  graph.addEdge('AD', 'AS', 'shape')
  graph.addEdge('AE', 'AL', 'shape')
  graph.addEdge('AF', 'AW', 'shape')
  graph.addEdge('AG', 'AO', 'shape')
  graph.addEdge('AH', 'AP', 'shape')
  graph.addEdge('AI', 'AJ', 'shape')
  graph.addEdge('AJ', 'AK', 'shape')
  graph.addEdge('AK', 'AL', 'shape')
  graph.addEdge('AL', 'AM', 'shape')
  graph.addEdge('AM', 'AN', 'shape')
  graph.addEdge('AN', 'AO', 'shape')
  graph.addEdge('AO', 'AX', 'shape')
  graph.addEdge('AP', 'AQ', 'shape')
  graph.addEdge('AQ', 'AR', 'shape')
  graph.addEdge('AR', 'AS', 'shape')
  graph.addEdge('AS', 'AT', 'shape')
  graph.addEdge('AT', 'AU', 'shape')
  graph.addEdge('AU', 'AW', 'shape')
  graph.addEdge('AW', 'AY', 'shape')
  graph.addEdge('AX', 'AZ', 'shape')
  graph.addEdge('AY', 'endA', 'shape')
  graph.addEdge('AZ', 'endB', 'shape')

  return graph
}

function swapperSameISharedO(): SimulatorGraph {
  const graph = new SimulatorGraph()

  graph.addNode(new Generator({ id: 'shx' }, createShapeProduct(codeToShape('CrRgSbWm'))))
  graph.addNode(new Generator({ id: 'shy' }, createShapeProduct(codeToShape('SbWmCrRg'))))
  graph.addNode(new Belt({ id: 'A' }))
  graph.addNode(new Belt({ id: 'B' }))
  graph.addNode(new Belt({ id: 'C' }))
  graph.addNode(new Belt({ id: 'D' }))
  graph.addNode(new Belt({ id: 'E' }))
  graph.addNode(new Belt({ id: 'F' }))
  graph.addNode(new Belt({ id: 'G' }))
  graph.addNode(new Belt({ id: 'H' }))
  graph.addNode(new Belt({ id: 'I' }))
  graph.addNode(new Belt({ id: 'J' }))
  graph.addNode(new Belt({ id: 'K' }))
  graph.addNode(new Belt({ id: 'L' }))
  graph.addNode(new Belt({ id: 'M' }))
  graph.addNode(new Belt({ id: 'N' }))
  graph.addNode(new Belt({ id: 'O' }))
  graph.addNode(new Belt({ id: 'P' }))
  graph.addNode(new Belt({ id: 'Q' }))
  graph.addNode(new Belt({ id: 'R' }))
  graph.addNode(new Belt({ id: 'S' }))
  graph.addNode(new Belt({ id: 'T' }))
  graph.addNode(new Belt({ id: 'U' }))
  graph.addNode(new Belt({ id: 'V' }))
  graph.addNode(new Belt({ id: 'W' }))
  graph.addNode(new Belt({ id: 'X' }))
  graph.addNode(new Swapper({ id: 'Y' }))
  graph.addNode(new Swapper({ id: 'Z' }))
  graph.addNode(new Swapper({ id: 'AA' }))
  graph.addNode(new Belt({ id: 'AB' }))
  graph.addNode(new Belt({ id: 'AC' }))
  graph.addNode(new Belt({ id: 'AD' }))
  graph.addNode(new Belt({ id: 'AE' }))
  graph.addNode(new Belt({ id: 'AF' }))
  graph.addNode(new Belt({ id: 'AG' }))
  graph.addNode(new Belt({ id: 'AH' }))
  graph.addNode(new Belt({ id: 'AI' }))
  graph.addNode(new Belt({ id: 'AJ' }))
  graph.addNode(new Trash({ id: 'end' }))
  
  graph.addEdge('shx', 'A', 'shape')
  graph.addEdge('shy', 'B', 'shape')
  graph.addEdge('A', 'C', 'shape')
  graph.addEdge('B', 'D', 'shape')
  graph.addEdge('C', 'K', 'shape')
  graph.addEdge('D', 'E', 'shape')
  graph.addEdge('D', 'T', 'shape')
  graph.addEdge('E', 'F', 'shape')
  graph.addEdge('F', 'G', 'shape')
  graph.addEdge('G', 'H', 'shape')
  graph.addEdge('G', 'V', 'shape')
  graph.addEdge('H', 'I', 'shape')
  graph.addEdge('I', 'J', 'shape')
  graph.addEdge('J', 'R', 'shape')
  graph.addEdge('K', 'S', 'shape')
  graph.addEdge('K', 'L', 'shape')
  graph.addEdge('L', 'M', 'shape')
  graph.addEdge('M', 'N', 'shape')
  graph.addEdge('N', 'U', 'shape')
  graph.addEdge('N', 'O', 'shape')
  graph.addEdge('O', 'P', 'shape')
  graph.addEdge('P', 'Q', 'shape')
  graph.addEdge('Q', 'W', 'shape')
  graph.addEdge('R', 'X', 'shape')
  graph.addEdge('S', 'Y', 'shape', 0)
  graph.addEdge('T', 'Y', 'shape', 1)
  graph.addEdge('U', 'Z', 'shape', 0)
  graph.addEdge('V', 'Z', 'shape', 1)
  graph.addEdge('W', 'AA', 'shape' , 0)
  graph.addEdge('X', 'AA', 'shape' , 1)
  graph.addEdge('Y', 'AB', 'shape', undefined, 0)
  graph.addEdge('Y', 'AC', 'shape', undefined, 1)
  graph.addEdge('Z', 'AE', 'shape', undefined, 0)
  graph.addEdge('Z', 'AF', 'shape', undefined, 1)
  graph.addEdge('AA', 'AH', 'shape', undefined, 0)
  graph.addEdge('AA', 'AI', 'shape', undefined, 1)
  graph.addEdge('AB', 'AC', 'shape')
  graph.addEdge('AC', 'AD', 'shape')
  graph.addEdge('AD', 'AE', 'shape')
  graph.addEdge('AE', 'AF', 'shape')
  graph.addEdge('AF', 'AG', 'shape')
  graph.addEdge('AG', 'AH', 'shape')
  graph.addEdge('AH', 'AI', 'shape')
  graph.addEdge('AI', 'AJ', 'shape')
  graph.addEdge('AJ', 'end', 'shape')

  return graph
}

function swapperSharedISameO(): SimulatorGraph {
  const graph = new SimulatorGraph()

  graph.addNode(new Generator({ id: 'shx' }, createShapeProduct(codeToShape('CrRgSbWm'))))
  graph.addNode(new Belt({ id: 'A' }))
  graph.addNode(new Belt({ id: 'B' }))
  graph.addNode(new Belt({ id: 'C' }))
  graph.addNode(new Belt({ id: 'D' }))
  graph.addNode(new Belt({ id: 'E' }))
  graph.addNode(new Belt({ id: 'F' }))
  graph.addNode(new Belt({ id: 'G' }))
  graph.addNode(new Belt({ id: 'H' }))
  graph.addNode(new Belt({ id: 'I' }))
  graph.addNode(new Swapper({ id: 'J' }))
  graph.addNode(new Swapper({ id: 'K' }))
  graph.addNode(new Swapper({ id: 'L' }))
  graph.addNode(new Belt({ id: 'M' }))
  graph.addNode(new Belt({ id: 'N' }))
  graph.addNode(new Belt({ id: 'O' }))
  graph.addNode(new Belt({ id: 'P' }))
  graph.addNode(new Belt({ id: 'Q' }))
  graph.addNode(new Belt({ id: 'R' }))
  graph.addNode(new Belt({ id: 'S' }))
  graph.addNode(new Belt({ id: 'T' }))
  graph.addNode(new Belt({ id: 'U' }))
  graph.addNode(new Belt({ id: 'V' }))
  graph.addNode(new Belt({ id: 'W' }))
  graph.addNode(new Belt({ id: 'X' }))
  graph.addNode(new Belt({ id: 'Y' }))
  graph.addNode(new Belt({ id: 'Z' }))
  graph.addNode(new Belt({ id: 'AA' }))
  graph.addNode(new Belt({ id: 'AB' }))
  graph.addNode(new Belt({ id: 'AC' }))
  graph.addNode(new Belt({ id: 'AD' }))
  graph.addNode(new Belt({ id: 'AE' }))
  graph.addNode(new Belt({ id: 'AF' }))
  graph.addNode(new Belt({ id: 'AG' }))
  graph.addNode(new Belt({ id: 'AH' }))
  graph.addNode(new Belt({ id: 'AI' }))
  graph.addNode(new Belt({ id: 'AJ' }))
  graph.addNode(new Trash({ id: 'endA' }))
  graph.addNode(new Trash({ id: 'endB' }))
  
  graph.addEdge('shx', 'A', 'shape')
  graph.addEdge('A', 'B', 'shape')
  graph.addEdge('B', 'C', 'shape')
  graph.addEdge('C', 'D', 'shape')
  graph.addEdge('D', 'E', 'shape')
  graph.addEdge('E', 'F', 'shape')
  graph.addEdge('F', 'G', 'shape')
  graph.addEdge('G', 'H', 'shape')
  graph.addEdge('H', 'I', 'shape')
  graph.addEdge('B', 'J', 'shape', 0)
  graph.addEdge('C', 'J', 'shape', 1)
  graph.addEdge('E', 'K', 'shape', 0)
  graph.addEdge('F', 'K', 'shape', 1)
  graph.addEdge('H', 'L', 'shape', 0)
  graph.addEdge('I', 'L', 'shape', 1)
  graph.addEdge('J', 'M', 'shape', undefined, 0)
  graph.addEdge('J', 'N', 'shape', undefined, 1)
  graph.addEdge('K', 'O', 'shape', undefined, 0)
  graph.addEdge('K', 'P', 'shape', undefined, 1)
  graph.addEdge('L', 'Q', 'shape', undefined, 0)
  graph.addEdge('L', 'R', 'shape', undefined, 1)
  graph.addEdge('M', 'S', 'shape')
  graph.addEdge('N', 'T', 'shape')
  graph.addEdge('O', 'AD', 'shape')
  graph.addEdge('P', 'W', 'shape')
  graph.addEdge('Q', 'AG', 'shape')
  graph.addEdge('R', 'Z', 'shape')
  graph.addEdge('S', 'AA', 'shape')
  graph.addEdge('T', 'U', 'shape')
  graph.addEdge('U', 'V', 'shape')
  graph.addEdge('V', 'W', 'shape')
  graph.addEdge('W', 'X', 'shape')
  graph.addEdge('X', 'Y', 'shape')
  graph.addEdge('Y', 'Z', 'shape')
  graph.addEdge('Z', 'AH', 'shape')
  graph.addEdge('AA', 'AB', 'shape')
  graph.addEdge('AB', 'AC', 'shape')
  graph.addEdge('AC', 'AD', 'shape')
  graph.addEdge('AD', 'AE', 'shape')
  graph.addEdge('AE', 'AF', 'shape')
  graph.addEdge('AF', 'AG', 'shape')
  graph.addEdge('AG', 'AI', 'shape')
  graph.addEdge('AH', 'AJ', 'shape')
  graph.addEdge('AI', 'endA', 'shape')
  graph.addEdge('AJ', 'endB', 'shape')

  return graph
}

function swapperSameIMixedO(): SimulatorGraph {
  const graph = new SimulatorGraph()

  graph.addNode(new Generator({ id: 'shx' }, createShapeProduct(codeToShape('CrRgSbWm'))))
  graph.addNode(new Generator({ id: 'shy' }, createShapeProduct(codeToShape('SbWmCrRg'))))
  graph.addNode(new Belt({ id: 'A' }))
  graph.addNode(new Belt({ id: 'B' }))
  graph.addNode(new Belt({ id: 'C' }))
  graph.addNode(new Belt({ id: 'D' }))
  graph.addNode(new Belt({ id: 'E' }))
  graph.addNode(new Belt({ id: 'F' }))
  graph.addNode(new Belt({ id: 'G' }))
  graph.addNode(new Belt({ id: 'H' }))
  graph.addNode(new Belt({ id: 'I' }))
  graph.addNode(new Belt({ id: 'J' }))
  graph.addNode(new Belt({ id: 'K' }))
  graph.addNode(new Belt({ id: 'L' }))
  graph.addNode(new Belt({ id: 'M' }))
  graph.addNode(new Belt({ id: 'N' }))
  graph.addNode(new Belt({ id: 'O' }))
  graph.addNode(new Belt({ id: 'P' }))
  graph.addNode(new Belt({ id: 'Q' }))
  graph.addNode(new Belt({ id: 'R' }))
  graph.addNode(new Belt({ id: 'S' }))
  graph.addNode(new Belt({ id: 'T' }))
  graph.addNode(new Belt({ id: 'U' }))
  graph.addNode(new Belt({ id: 'V' }))
  graph.addNode(new Belt({ id: 'W' }))
  graph.addNode(new Belt({ id: 'X' }))
  graph.addNode(new Swapper({ id: 'Y' }))
  graph.addNode(new Swapper({ id: 'Z' }))
  graph.addNode(new Swapper({ id: 'AA' }))
  graph.addNode(new Belt({ id: 'AB' }))
  graph.addNode(new Belt({ id: 'AC' }))
  graph.addNode(new Belt({ id: 'AD' }))
  graph.addNode(new Belt({ id: 'AE' }))
  graph.addNode(new Belt({ id: 'AF' }))
  graph.addNode(new Belt({ id: 'AG' }))
  graph.addNode(new Belt({ id: 'AH' }))
  graph.addNode(new Belt({ id: 'AI' }))
  graph.addNode(new Belt({ id: 'AJ' }))
  graph.addNode(new Belt({ id: 'AK' }))
  graph.addNode(new Belt({ id: 'AL' }))
  graph.addNode(new Belt({ id: 'AM' }))
  graph.addNode(new Belt({ id: 'AN' }))
  graph.addNode(new Belt({ id: 'AO' }))
  graph.addNode(new Belt({ id: 'AP' }))
  graph.addNode(new Belt({ id: 'AQ' }))
  graph.addNode(new Belt({ id: 'AR' }))
  graph.addNode(new Trash({ id: 'endA' }))
  graph.addNode(new Trash({ id: 'endB' }))
  graph.addNode(new Trash({ id: 'endC' }))
  
  graph.addEdge('shx', 'A', 'shape')
  graph.addEdge('shy', 'B', 'shape')
  graph.addEdge('A', 'C', 'shape')
  graph.addEdge('B', 'D', 'shape')
  graph.addEdge('C', 'K', 'shape')
  graph.addEdge('D', 'E', 'shape')
  graph.addEdge('D', 'T', 'shape')
  graph.addEdge('E', 'F', 'shape')
  graph.addEdge('F', 'G', 'shape')
  graph.addEdge('G', 'H', 'shape')
  graph.addEdge('G', 'V', 'shape')
  graph.addEdge('H', 'I', 'shape')
  graph.addEdge('I', 'J', 'shape')
  graph.addEdge('J', 'R', 'shape')
  graph.addEdge('K', 'S', 'shape')
  graph.addEdge('K', 'L', 'shape')
  graph.addEdge('L', 'M', 'shape')
  graph.addEdge('M', 'N', 'shape')
  graph.addEdge('N', 'U', 'shape')
  graph.addEdge('N', 'O', 'shape')
  graph.addEdge('O', 'P', 'shape')
  graph.addEdge('P', 'Q', 'shape')
  graph.addEdge('Q', 'W', 'shape')
  graph.addEdge('R', 'X', 'shape')
  graph.addEdge('S', 'Y', 'shape', 0)
  graph.addEdge('T', 'Y', 'shape', 1)
  graph.addEdge('U', 'Z', 'shape', 0)
  graph.addEdge('V', 'Z', 'shape', 1)
  graph.addEdge('W', 'AA', 'shape' , 0)
  graph.addEdge('X', 'AA', 'shape' , 1)
  graph.addEdge('Y', 'AB', 'shape', undefined, 0)
  graph.addEdge('Y', 'AC', 'shape', undefined, 1)
  graph.addEdge('Z', 'AD', 'shape', undefined, 0)
  graph.addEdge('Z', 'AE', 'shape', undefined, 1)
  graph.addEdge('AA', 'AG', 'shape', undefined, 0)
  graph.addEdge('AA', 'AH', 'shape', undefined, 1)
  graph.addEdge('AB', 'AI', 'shape')
  graph.addEdge('AC', 'AJ', 'shape')
  graph.addEdge('AD', 'AF', 'shape')
  graph.addEdge('AE', 'AK', 'shape')
  graph.addEdge('AF', 'AG', 'shape')
  graph.addEdge('AG', 'AH', 'shape')
  graph.addEdge('AH', 'AL', 'shape')
  graph.addEdge('AI', 'AM', 'shape')
  graph.addEdge('AK', 'AQ', 'shape')
  graph.addEdge('AL', 'AR', 'shape')
  graph.addEdge('AN', 'AM', 'shape')
  graph.addEdge('AO', 'AN', 'shape')
  graph.addEdge('AP', 'AQ', 'shape')
  graph.addEdge('AJ', 'endA', 'shape')
  graph.addEdge('AM', 'endB', 'shape')
  graph.addEdge('AR', 'endC', 'shape')

  return graph
}

function swapperMixedISameO(): SimulatorGraph {
  const graph = new SimulatorGraph()

  graph.addNode(new Generator({ id: 'shx' }, createShapeProduct(codeToShape('CrRgSbWm'))))
  graph.addNode(new Generator({ id: 'shy' }, createShapeProduct(codeToShape('SbWmCrRg'))))
  graph.addNode(new Belt({ id: 'A' }))
  graph.addNode(new Belt({ id: 'B' }))
  graph.addNode(new Belt({ id: 'C' }))
  graph.addNode(new Belt({ id: 'D' }))
  graph.addNode(new Belt({ id: 'E' }))
  graph.addNode(new Belt({ id: 'F' }))
  graph.addNode(new Belt({ id: 'G' }))
  graph.addNode(new Belt({ id: 'H' }))
  graph.addNode(new Belt({ id: 'I' }))
  graph.addNode(new Belt({ id: 'J' }))
  graph.addNode(new Belt({ id: 'K' }))
  graph.addNode(new Belt({ id: 'L' }))
  graph.addNode(new Belt({ id: 'M' }))
  graph.addNode(new Belt({ id: 'N' }))
  graph.addNode(new Belt({ id: 'O' }))
  graph.addNode(new Belt({ id: 'P' }))
  graph.addNode(new Belt({ id: 'Q' }))
  graph.addNode(new Belt({ id: 'R' }))
  graph.addNode(new Belt({ id: 'S' }))
  graph.addNode(new Belt({ id: 'T' }))
  graph.addNode(new Belt({ id: 'U' }))
  graph.addNode(new Belt({ id: 'V' }))
  graph.addNode(new Belt({ id: 'W' }))
  graph.addNode(new Swapper({ id: 'X' }))
  graph.addNode(new Swapper({ id: 'Y' }))
  graph.addNode(new Swapper({ id: 'Z' }))
  graph.addNode(new Belt({ id: 'AA' }))
  graph.addNode(new Belt({ id: 'AB' }))
  graph.addNode(new Belt({ id: 'AC' }))
  graph.addNode(new Belt({ id: 'AD' }))
  graph.addNode(new Belt({ id: 'AE' }))
  graph.addNode(new Belt({ id: 'AF' }))
  graph.addNode(new Belt({ id: 'AG' }))
  graph.addNode(new Belt({ id: 'AH' }))
  graph.addNode(new Belt({ id: 'AI' }))
  graph.addNode(new Belt({ id: 'AJ' }))
  graph.addNode(new Belt({ id: 'AK' }))
  graph.addNode(new Belt({ id: 'AL' }))
  graph.addNode(new Belt({ id: 'AM' }))
  graph.addNode(new Belt({ id: 'AN' }))
  graph.addNode(new Belt({ id: 'AO' }))
  graph.addNode(new Belt({ id: 'AP' }))
  graph.addNode(new Belt({ id: 'AQ' }))
  graph.addNode(new Belt({ id: 'AR' }))
  graph.addNode(new Belt({ id: 'AS' }))
  graph.addNode(new Belt({ id: 'AT' }))
  graph.addNode(new Belt({ id: 'AU' }))
  graph.addNode(new Belt({ id: 'AV' }))
  graph.addNode(new Belt({ id: 'AW' }))
  graph.addNode(new Belt({ id: 'AX' }))
  graph.addNode(new Trash({ id: 'endA' }))
  graph.addNode(new Trash({ id: 'endB' }))
  
  graph.addEdge('shx', 'A', 'shape')
  graph.addEdge('shx', 'B', 'shape')
  graph.addEdge('A', 'C', 'shape')
  graph.addEdge('B', 'D', 'shape')
  graph.addEdge('C', 'J', 'shape')
  graph.addEdge('D', 'S', 'shape')
  graph.addEdge('D', 'E', 'shape')
  graph.addEdge('E', 'F', 'shape')
  graph.addEdge('F', 'G', 'shape')
  graph.addEdge('G', 'H', 'shape')
  graph.addEdge('G', 'U', 'shape')
  graph.addEdge('H', 'I', 'shape')
  graph.addEdge('I', 'V', 'shape')
  graph.addEdge('J', 'K', 'shape')
  graph.addEdge('J', 'R', 'shape')
  graph.addEdge('K', 'L', 'shape')
  graph.addEdge('L', 'M', 'shape')
  graph.addEdge('M', 'N', 'shape')
  graph.addEdge('M', 'T', 'shape')
  graph.addEdge('N', 'O', 'shape')
  graph.addEdge('O', 'P', 'shape')
  graph.addEdge('P', 'Q', 'shape')
  graph.addEdge('Q', 'W', 'shape')
  graph.addEdge('R', 'X', 'shape', 0)
  graph.addEdge('S', 'X', 'shape', 1)
  graph.addEdge('T', 'Y', 'shape', 0)
  graph.addEdge('U', 'Y', 'shape', 1)
  graph.addEdge('V', 'Z', 'shape', 0)
  graph.addEdge('W', 'Z', 'shape', 1)
  graph.addEdge('X', 'AA', 'shape', undefined, 0)
  graph.addEdge('X', 'AB', 'shape', undefined, 1)
  graph.addEdge('Y', 'AC', 'shape', undefined, 0)
  graph.addEdge('Y', 'AD', 'shape', undefined, 1)
  graph.addEdge('Z', 'AE', 'shape', undefined, 0)
  graph.addEdge('Z', 'AF', 'shape', undefined, 1)
  graph.addEdge('AA', 'AG', 'shape')
  graph.addEdge('AB', 'AH', 'shape')
  graph.addEdge('AC', 'AR', 'shape')
  graph.addEdge('AD', 'AK', 'shape')
  graph.addEdge('AE', 'AU', 'shape')
  graph.addEdge('AF', 'AN', 'shape')
  graph.addEdge('AG', 'AO', 'shape')
  graph.addEdge('AH', 'AI', 'shape')
  graph.addEdge('AI', 'AJ', 'shape')
  graph.addEdge('AJ', 'AK', 'shape')
  graph.addEdge('AK', 'AL', 'shape')
  graph.addEdge('AL', 'AM', 'shape')
  graph.addEdge('AM', 'AN', 'shape')
  graph.addEdge('AN', 'AV', 'shape')
  graph.addEdge('AO', 'AP', 'shape')
  graph.addEdge('AP', 'AQ', 'shape')
  graph.addEdge('AQ', 'AR', 'shape')
  graph.addEdge('AR', 'AS', 'shape')
  graph.addEdge('AS', 'AT', 'shape')
  graph.addEdge('AT', 'AU', 'shape')
  graph.addEdge('AU', 'AW', 'shape')
  graph.addEdge('AV', 'AX', 'shape')
  graph.addEdge('AW', 'endA', 'shape')
  graph.addEdge('AX', 'endB', 'shape')

  return graph
}

function beltRedundantSplit(): SimulatorGraph {
  const graph = new SimulatorGraph()

  graph.addNode(new Generator({ id: 'shx' }, createShapeProduct(codeToShape('CrRgSbWm'))))
  graph.addNode(new Belt({ id: 'A' }))
  graph.addNode(new Belt({ id: 'B' }))
  graph.addNode(new Belt({ id: 'C' }))
  graph.addNode(new Belt({ id: 'D' }))
  graph.addNode(new Belt({ id: 'E' }))
  graph.addNode(new Belt({ id: 'F' }))
  graph.addNode(new Belt({ id: 'G' }))
  graph.addNode(new Belt({ id: 'H' }))
  graph.addNode(new Belt({ id: 'I' }))
  graph.addNode(new Belt({ id: 'J' }))
  graph.addNode(new Belt({ id: 'K' }))
  graph.addNode(new Belt({ id: 'L' }))
  graph.addNode(new Belt({ id: 'M' }))
  graph.addNode(new Belt({ id: 'N' }))
  graph.addNode(new Trash({ id: 'end' }))
  
  graph.addEdge('shx', 'A', 'shape')
  graph.addEdge('A', 'B', 'shape')
  graph.addEdge('B', 'C', 'shape')
  graph.addEdge('B', 'F', 'shape')
  graph.addEdge('C', 'D', 'shape')
  graph.addEdge('C', 'G', 'shape')
  graph.addEdge('D', 'E', 'shape')
  graph.addEdge('D', 'H', 'shape')
  graph.addEdge('E', 'I', 'shape')
  graph.addEdge('F', 'J', 'shape')
  graph.addEdge('G', 'K', 'shape')
  graph.addEdge('H', 'L', 'shape')
  graph.addEdge('I', 'M', 'shape')
  graph.addEdge('J', 'N', 'shape')
  graph.addEdge('K', 'J', 'shape')
  graph.addEdge('L', 'K', 'shape')
  graph.addEdge('M', 'L', 'shape')
  graph.addEdge('N', 'end', 'shape')

  return graph
}

function beltMerge(): SimulatorGraph {
  const graph = new SimulatorGraph()

  graph.addNode(new Generator({ id: 'shx' }, createShapeProduct(codeToShape('CrRgSbWm'))))
  graph.addNode(new Generator({ id: 'shy' }, createShapeProduct(codeToShape('RbSyCrWy'))))
  graph.addNode(new Belt({ id: 'A' }))
  graph.addNode(new Belt({ id: 'B' }))
  graph.addNode(new Belt({ id: 'C' }))
  graph.addNode(new Belt({ id: 'D' }))
  graph.addNode(new Belt({ id: 'E' }))
  graph.addNode(new Belt({ id: 'F' }))
  graph.addNode(new Belt({ id: 'G' }))
  graph.addNode(new Belt({ id: 'H' }))
  graph.addNode(new Belt({ id: 'I' }))
  graph.addNode(new Belt({ id: 'J' }))
  graph.addNode(new Belt({ id: 'K' }))
  graph.addNode(new Belt({ id: 'L' }))
  graph.addNode(new Belt({ id: 'M' }))
  graph.addNode(new Belt({ id: 'N' }))
  graph.addNode(new Trash({ id: 'end' }))
  
  graph.addEdge('shx', 'A', 'shape')
  graph.addEdge('shy', 'B', 'shape')
  graph.addEdge('A', 'C', 'shape')
  graph.addEdge('B', 'E', 'shape')
  graph.addEdge('C', 'D', 'shape')
  graph.addEdge('C', 'F', 'shape')
  graph.addEdge('D', 'G', 'shape')
  graph.addEdge('E', 'D', 'shape')
  graph.addEdge('E', 'H', 'shape')
  graph.addEdge('F', 'I', 'shape')
  graph.addEdge('G', 'J', 'shape')
  graph.addEdge('H', 'K', 'shape')
  graph.addEdge('I', 'L', 'shape')
  graph.addEdge('J', 'I', 'shape')
  graph.addEdge('K', 'N', 'shape')
  graph.addEdge('M', 'L', 'shape')
  graph.addEdge('N', 'M', 'shape')
  graph.addEdge('L', 'end', 'shape')

  return graph
}

function beltBalancer(): SimulatorGraph {
  const graph = new SimulatorGraph()

  graph.addNode(new Generator({ id: 'shx' }, createShapeProduct(codeToShape('CrRgSbWm'))))
  graph.addNode(new Generator({ id: 'shy' }, createShapeProduct(codeToShape('RbSyCrWy'))))
  graph.addNode(new Belt({ id: 'A' }))
  graph.addNode(new Belt({ id: 'B' }))
  graph.addNode(new Belt({ id: 'C' }))
  graph.addNode(new Belt({ id: 'D' }))
  graph.addNode(new Belt({ id: 'E' }))
  graph.addNode(new Belt({ id: 'F' }))
  graph.addNode(new Belt({ id: 'G' }))
  graph.addNode(new Belt({ id: 'H' }))
  graph.addNode(new Belt({ id: 'I' }))
  graph.addNode(new Belt({ id: 'J' }))
  graph.addNode(new Trash({ id: 'endA' }))
  graph.addNode(new Trash({ id: 'endB' }))
  
  graph.addEdge('shx', 'A', 'shape')
  graph.addEdge('shy', 'B', 'shape')
  graph.addEdge('A', 'C', 'shape')
  graph.addEdge('B', 'E', 'shape')
  graph.addEdge('C', 'D', 'shape')
  graph.addEdge('C', 'F', 'shape')
  graph.addEdge('D', 'G', 'shape')
  graph.addEdge('E', 'D', 'shape')
  graph.addEdge('E', 'H', 'shape')
  graph.addEdge('F', 'H', 'shape')
  graph.addEdge('G', 'I', 'shape')
  graph.addEdge('H', 'J', 'shape')
  graph.addEdge('I', 'endA', 'shape')
  graph.addEdge('J', 'endB', 'shape')

  return graph
}

function parallelCutter(): SimulatorGraph {
  const graph = new SimulatorGraph()

  graph.addNode(new Generator({ id: 'shx' }, createShapeProduct(codeToShape('CrRgSbWm'))))
  graph.addNode(new Belt({ id: 'A' }))
  graph.addNode(new Belt({ id: 'B' }))
  graph.addNode(new Belt({ id: 'C' }))
  graph.addNode(new Belt({ id: 'D' }))
  graph.addNode(new Belt({ id: 'E' }))
  graph.addNode(new Cutter({ id: 'F' }))
  graph.addNode(new Cutter({ id: 'G' }))
  graph.addNode(new Belt({ id: 'H' }))
  graph.addNode(new Rotator({ id: 'I' }))
  graph.addNode(new Belt({ id: 'J' }))
  graph.addNode(new Rotator({ id: 'K' }))
  graph.addNode(new Belt({ id: 'L' }))
  graph.addNode(new Belt({ id: 'M' }))
  graph.addNode(new Belt({ id: 'N' }))
  graph.addNode(new Belt({ id: 'O' }))
  graph.addNode(new Belt({ id: 'P' }))
  graph.addNode(new Belt({ id: 'Q' }))
  graph.addNode(new Trash({ id: 'end' }))

  graph.addEdge('shx', 'A', 'shape')
  graph.addEdge('A', 'B', 'shape')
  graph.addEdge('B', 'C', 'shape')
  graph.addEdge('B', 'F', 'shape')
  graph.addEdge('C', 'D', 'shape')
  graph.addEdge('D', 'E', 'shape')
  graph.addEdge('E', 'G', 'shape')
  graph.addEdge('F', 'H', 'shape', undefined, 0)
  graph.addEdge('F', 'I', 'shape', undefined, 1)
  graph.addEdge('G', 'J', 'shape', undefined, 0)
  graph.addEdge('G', 'K', 'shape', undefined, 1)
  graph.addEdge('H', 'L', 'shape')
  graph.addEdge('I', 'M', 'shape')
  graph.addEdge('J', 'O', 'shape')
  graph.addEdge('K', 'P', 'shape')
  graph.addEdge('L', 'Q', 'shape')
  graph.addEdge('M', 'L', 'shape')
  graph.addEdge('N', 'M', 'shape')
  graph.addEdge('O', 'N', 'shape')
  graph.addEdge('P', 'O', 'shape')
  graph.addEdge('Q', 'end', 'shape')

  return graph
}

function paralelStacker(): SimulatorGraph {
  const graph = new SimulatorGraph()

  graph.addNode(new Generator({ id: 'shx' }, createShapeProduct(codeToShape('CrRgSbWm'))))
  graph.addNode(new Belt({ id: 'A' }))
  graph.addNode(new Belt({ id: 'B' }))
  graph.addNode(new Belt({ id: 'C' }))
  graph.addNode(new Belt({ id: 'D' }))
  graph.addNode(new Belt({ id: 'E' }))
  graph.addNode(new Belt({ id: 'F' }))
  graph.addNode(new Belt({ id: 'G' }))
  graph.addNode(new Belt({ id: 'H' }))
  graph.addNode(new Belt({ id: 'I' }))
  graph.addNode(new Stacker({ id: 'J' }))
  graph.addNode(new Belt({ id: 'K' }))
  graph.addNode(new Stacker({ id: 'L' }))
  graph.addNode(new Belt({ id: 'M' }))
  graph.addNode(new Stacker({ id: 'N' }))
  graph.addNode(new Belt({ id: 'O' }))
  graph.addNode(new Stacker({ id: 'P' }))
  graph.addNode(new Belt({ id: 'Q' }))
  graph.addNode(new Rotator({ id: 'R' }))
  graph.addNode(new Rotator({ id: 'S' }))
  graph.addNode(new Belt({ id: 'T' }))
  graph.addNode(new Belt({ id: 'U' }))
  graph.addNode(new Belt({ id: 'V' }))
  graph.addNode(new Belt({ id: 'W' }))
  graph.addNode(new Belt({ id: 'X' }))
  graph.addNode(new Belt({ id: 'Y' }))
  graph.addNode(new Trash({ id: 'endA' }))
  graph.addNode(new Trash({ id: 'endB' }))
  graph.addNode(new Trash({ id: 'endC' }))
  
  graph.addEdge('shx', 'A', 'shape')
  graph.addEdge('A', 'B', 'shape')
  graph.addEdge('B', 'C', 'shape')
  graph.addEdge('B', 'J', 'shape', 0)
  graph.addEdge('C', 'K', 'shape')
  graph.addEdge('C', 'D', 'shape')
  graph.addEdge('D', 'L', 'shape', 0)
  graph.addEdge('D', 'E', 'shape')
  graph.addEdge('E', 'M', 'shape')
  graph.addEdge('E', 'F', 'shape')
  graph.addEdge('F', 'N', 'shape', 0)
  graph.addEdge('F', 'G', 'shape')
  graph.addEdge('G', 'O', 'shape')
  graph.addEdge('G', 'H', 'shape')
  graph.addEdge('H', 'P', 'shape', 0)
  graph.addEdge('H', 'I', 'shape')
  graph.addEdge('I', 'Q', 'shape')
  graph.addEdge('J', 'R', 'shape')
  graph.addEdge('K', 'J', 'shape', 1)
  graph.addEdge('L', 'S', 'shape')
  graph.addEdge('M', 'L', 'shape', 1)
  graph.addEdge('N', 'T', 'shape')
  graph.addEdge('O', 'N', 'shape', 1)
  graph.addEdge('P', 'V', 'shape')
  graph.addEdge('Q', 'P', 'shape', 1)
  graph.addEdge('R', 'W', 'shape')
  graph.addEdge('S', 'X', 'shape')
  graph.addEdge('T', 'Y', 'shape')
  graph.addEdge('U', 'T', 'shape')
  graph.addEdge('V', 'U', 'shape')
  graph.addEdge('W', 'endA', 'shape')
  graph.addEdge('X', 'endB', 'shape')
  graph.addEdge('Y', 'endC', 'shape')

  return graph
}

function mixerAndPainter(): SimulatorGraph {
  const graph = new SimulatorGraph()

  graph.addNode(new Generator({ id: 'shx' }, createShapeProduct(codeToShape('CrRgSbWm'))))
  graph.addNode(new Generator({ id: 'flr' }, createColorProduct('r', 1200)))
  graph.addNode(new Generator({ id: 'flb' }, createColorProduct('b', 1200)))
  graph.addNode(new Pipe({ id: 'A' }))
  graph.addNode(new Pipe({ id: 'B' }))
  graph.addNode(new Pipe({ id: 'C' }))
  graph.addNode(new Pipe({ id: 'D' }))
  graph.addNode(new Pipe({ id: 'E' }))
  graph.addNode(new Pipe({ id: 'F' }))
  graph.addNode(new Pipe({ id: 'G' }))
  graph.addNode(new Pipe({ id: 'H' }))
  graph.addNode(new Pipe({ id: 'I' }))
  graph.addNode(new Pipe({ id: 'J' }))
  graph.addNode(new Pipe({ id: 'K' }))
  graph.addNode(new Pipe({ id: 'L' }))
  graph.addNode(new ColorMixer({ id: 'M' }))
  graph.addNode(new ColorMixer({ id: 'N' }))
  graph.addNode(new Pipe({ id: 'O' }))
  graph.addNode(new Pipe({ id: 'P' }))
  graph.addNode(new Pipe({ id: 'Q' }))
  graph.addNode(new Pipe({ id: 'R' }))
  graph.addNode(new Pipe({ id: 'S' }))
  graph.addNode(new Pipe({ id: 'T' }))
  graph.addNode(new Pipe({ id: 'U' }))
  graph.addNode(new Pipe({ id: 'V' }))
  graph.addNode(new Pipe({ id: 'W' }))
  graph.addNode(new Pipe({ id: 'X' }))
  graph.addNode(new Pipe({ id: 'Y' }))
  graph.addNode(new Pipe({ id: 'Z' }))
  graph.addNode(new Pipe({ id: 'AA' }))
  graph.addNode(new Pipe({ id: 'AB' }))
  graph.addNode(new Pipe({ id: 'AC' }))
  graph.addNode(new Belt({ id: 'AD' }))
  graph.addNode(new Belt({ id: 'AE' }))
  graph.addNode(new Belt({ id: 'AF' }))
  graph.addNode(new Belt({ id: 'AG' }))
  graph.addNode(new Belt({ id: 'AH' }))
  graph.addNode(new Belt({ id: 'AI' }))
  graph.addNode(new Belt({ id: 'AJ' }))
  graph.addNode(new Belt({ id: 'AK' }))
  graph.addNode(new Belt({ id: 'AL' }))
  graph.addNode(new Belt({ id: 'AM' }))
  graph.addNode(new Belt({ id: 'AN' }))
  graph.addNode(new Belt({ id: 'AO' }))
  graph.addNode(new Belt({ id: 'AP' }))
  graph.addNode(new Belt({ id: 'AQ' }))
  graph.addNode(new Belt({ id: 'AR' }))
  graph.addNode(new Belt({ id: 'AS' }))
  graph.addNode(new Painter({ id: 'AT' }))
  graph.addNode(new Painter({ id: 'AU' }))
  graph.addNode(new Painter({ id: 'AV' }))
  graph.addNode(new Painter({ id: 'AW' }))
  graph.addNode(new Belt({ id: 'AX' }))
  graph.addNode(new Belt({ id: 'AY' }))
  graph.addNode(new Belt({ id: 'AZ' }))
  graph.addNode(new Belt({ id: 'BA' }))
  graph.addNode(new Belt({ id: 'BB' }))
  graph.addNode(new Belt({ id: 'BC' }))
  graph.addNode(new Belt({ id: 'BD' }))
  graph.addNode(new Belt({ id: 'BE' }))
  graph.addNode(new Belt({ id: 'BF' }))
  graph.addNode(new Belt({ id: 'BG' }))
  graph.addNode(new Belt({ id: 'BH' }))
  graph.addNode(new Trash({ id: 'end' }))
  
  graph.addEdge('flr', 'A', 'color')
  graph.addEdge('flb', 'B', 'color')
  graph.addEdge('shx', 'AD', 'shape')
  graph.addEdge('A', 'C', 'color')
  graph.addEdge('B', 'D', 'color')
  graph.addEdge('C', 'H', 'color')
  graph.addEdge('D', 'E', 'color')
  graph.addEdge('D', 'M', 'color', 1)
  graph.addEdge('E', 'F', 'color')
  graph.addEdge('F', 'G', 'color')
  graph.addEdge('G', 'L', 'color')
  graph.addEdge('H', 'M', 'color', 0)
  graph.addEdge('H', 'I', 'color')
  graph.addEdge('I', 'J', 'color')
  graph.addEdge('J', 'K', 'color')
  graph.addEdge('K', 'N', 'color', 0)
  graph.addEdge('L', 'N', 'color', 1)
  graph.addEdge('M', 'O', 'color')
  graph.addEdge('N', 'R', 'color')
  graph.addEdge('O', 'P', 'color')
  graph.addEdge('P', 'Z', 'color')
  graph.addEdge('Q', 'P', 'color')
  graph.addEdge('R', 'Q', 'color')
  graph.addEdge('R', 'S', 'color')
  graph.addEdge('S', 'AA', 'color')
  graph.addEdge('S', 'T', 'color')
  graph.addEdge('T', 'U', 'color')
  graph.addEdge('U', 'V', 'color')
  graph.addEdge('V', 'AB', 'color')
  graph.addEdge('V', 'W', 'color')
  graph.addEdge('W', 'X', 'color')
  graph.addEdge('X', 'Y', 'color')
  graph.addEdge('Y', 'AC', 'color')
  graph.addEdge('Z', 'AT', 'color')
  graph.addEdge('AA', 'AU', 'color')
  graph.addEdge('AB', 'AV', 'color')
  graph.addEdge('AC', 'AW', 'color')
  graph.addEdge('AD', 'AE', 'shape')
  graph.addEdge('AE', 'AF', 'shape')
  graph.addEdge('AF', 'AG', 'shape')
  graph.addEdge('AG', 'AH', 'shape')
  graph.addEdge('AH', 'AI', 'shape')
  graph.addEdge('AI', 'AS', 'shape')
  graph.addEdge('AJ', 'AT', 'shape')
  graph.addEdge('AK', 'AJ', 'shape')
  graph.addEdge('AL', 'AK', 'shape')
  graph.addEdge('AM', 'AL', 'shape')
  graph.addEdge('AM', 'AU', 'shape')
  graph.addEdge('AN', 'AM', 'shape')
  graph.addEdge('AO', 'AN', 'shape')
  graph.addEdge('AP', 'AO', 'shape')
  graph.addEdge('AP', 'AV', 'shape')
  graph.addEdge('AQ', 'AP', 'shape')
  graph.addEdge('AR', 'AQ', 'shape')
  graph.addEdge('AS', 'AR', 'shape')
  graph.addEdge('AS', 'AW', 'shape')
  graph.addEdge('AT', 'AX', 'shape')
  graph.addEdge('AU', 'BA', 'shape')
  graph.addEdge('AV', 'BD', 'shape')
  graph.addEdge('AW', 'BG', 'shape')
  graph.addEdge('AX', 'BH', 'shape')
  graph.addEdge('AY', 'AX', 'shape')
  graph.addEdge('AZ', 'AY', 'shape')
  graph.addEdge('BA', 'AZ', 'shape')
  graph.addEdge('BB', 'BA', 'shape')
  graph.addEdge('BC', 'BB', 'shape')
  graph.addEdge('BD', 'BC', 'shape')
  graph.addEdge('BE', 'BD', 'shape')
  graph.addEdge('BF', 'BE', 'shape')
  graph.addEdge('BG', 'BF', 'shape')
  graph.addEdge('BH', 'end', 'shape')
  
  return graph
}

function pipeSpaghetti(): SimulatorGraph {
  const graph = new SimulatorGraph()
  graph.addNode(new Generator({ id: 'flr' }, { color: 'r', amount: 1200 }))
  graph.addNode(new Generator({ id: 'flb' }, { color: 'b', amount: 1200 }))
  graph.addNode(new Pipe({ id: 'A' }))
  graph.addNode(new Pipe({ id: 'B' }))
  graph.addNode(new Pipe({ id: 'C' }))
  graph.addNode(new Pipe({ id: 'D' }))
  graph.addNode(new Pipe({ id: 'E' }))
  graph.addNode(new Pipe({ id: 'F' }))
  graph.addNode(new Pipe({ id: 'G' }))
  graph.addNode(new Pipe({ id: 'H' }))
  graph.addNode(new Pipe({ id: 'I' }))
  graph.addNode(new Pipe({ id: 'J' }))
  graph.addNode(new Pipe({ id: 'K' }))
  graph.addNode(new Pipe({ id: 'L' }))
  graph.addNode(new Pipe({ id: 'M' }))
  graph.addNode(new Pipe({ id: 'N' }))
  graph.addNode(new Pipe({ id: 'O' }))
  graph.addNode(new Pipe({ id: 'P' }))
  graph.addNode(new Pipe({ id: 'Q' }))
  graph.addNode(new Pipe({ id: 'R' }))
  graph.addNode(new ColorMixer({ id: 'S' }))
  graph.addNode(new ColorMixer({ id: 'T' }))
  graph.addNode(new ColorMixer({ id: 'U' }))
  graph.addNode(new Pipe({ id: 'V' }))
  graph.addNode(new Pipe({ id: 'W' }))
  graph.addNode(new Pipe({ id: 'X' }))
  graph.addNode(new Pipe({ id: 'Y' }))
  graph.addNode(new Pipe({ id: 'Z' }))
  graph.addNode(new Pipe({ id: 'AA' }))
  graph.addNode(new Pipe({ id: 'AB' }))
  graph.addNode(new Pipe({ id: 'AC' }))
  graph.addNode(new Pipe({ id: 'AD' }))
  graph.addNode(new Pipe({ id: 'AE' }))
  graph.addNode(new Pipe({ id: 'AF' }))
  graph.addNode(new Pipe({ id: 'AG' }))
  graph.addNode(new Pipe({ id: 'AH' }))
  graph.addNode(new Pipe({ id: 'AI' }))
  graph.addNode(new Trash({ id: 'endA' }))
  graph.addNode(new Trash({ id: 'endB' }))
  graph.addNode(new Trash({ id: 'endC' }))

  graph.addEdge('flr', 'A', 'color')
  graph.addEdge('flb', 'B', 'color')
  graph.addEdge('A', 'C', 'color')
  graph.addEdge('B', 'D', 'color')
  graph.addEdge('C', 'K', 'color')
  graph.addEdge('D', 'L', 'color')
  graph.addEdge('D', 'E', 'color')
  graph.addEdge('E', 'F', 'color')
  graph.addEdge('F', 'G', 'color')
  graph.addEdge('G', 'O', 'color')
  graph.addEdge('G', 'H', 'color')
  graph.addEdge('H', 'I', 'color')
  graph.addEdge('I', 'J', 'color')
  graph.addEdge('J', 'R', 'color')
  graph.addEdge('K', 'S', 'color', 0)
  graph.addEdge('K', 'M', 'color')
  graph.addEdge('L', 'S', 'color', 1)
  graph.addEdge('M', 'N', 'color')
  graph.addEdge('N', 'T', 'color', 0)
  graph.addEdge('N', 'P', 'color')
  graph.addEdge('O', 'T', 'color', 1)
  graph.addEdge('P', 'Q', 'color')
  graph.addEdge('Q', 'U', 'color', 0)
  graph.addEdge('R', 'U', 'color', 1)
  graph.addEdge('S', 'V', 'color')
  graph.addEdge('T', 'Y', 'color')
  graph.addEdge('U', 'AB', 'color')
  graph.addEdge('V', 'W', 'color')
  graph.addEdge('W', 'X', 'color')
  graph.addEdge('W', 'AD', 'color')
  graph.addEdge('X', 'Y', 'color')
  graph.addEdge('Y', 'Z', 'color')
  graph.addEdge('Z', 'AG', 'color')
  graph.addEdge('AA', 'Z', 'color')
  graph.addEdge('AB', 'AA', 'color')
  graph.addEdge('AD', 'AC', 'color')
  graph.addEdge('AD', 'AE', 'color')
  graph.addEdge('AE', 'AF', 'color')
  graph.addEdge('AG', 'AF', 'color')
  graph.addEdge('AG', 'AH', 'color')
  graph.addEdge('AH', 'AI', 'color')
  graph.addEdge('AC', 'endA', 'color')
  graph.addEdge('AF', 'endB', 'color')
  graph.addEdge('AI', 'endC', 'color')

  return graph
}

function deadEnds(): SimulatorGraph {
  const graph = new SimulatorGraph()
  graph.addNode(new Generator({ id: 'shx' }, createShapeProduct(codeToShape('CrRgSbWm'))))
  graph.addNode(new Belt({ id: 'A' }))
  graph.addNode(new Belt({ id: 'B' }))
  graph.addNode(new Belt({ id: 'C' }))
  graph.addNode(new Belt({ id: 'D' }))
  graph.addNode(new Belt({ id: 'E' }))
  graph.addNode(new Belt({ id: 'F' }))
  graph.addNode(new Belt({ id: 'G' }))
  graph.addNode(new Belt({ id: 'H' }))
  graph.addNode(new Belt({ id: 'I' }))
  graph.addNode(new Belt({ id: 'J' }))
  graph.addNode(new Belt({ id: 'K' }))
  graph.addNode(new Belt({ id: 'L' }))
  graph.addNode(new Belt({ id: 'M' }))
  graph.addNode(new Belt({ id: 'N' }))
  graph.addNode(new Belt({ id: 'O' }))
  graph.addNode(new Belt({ id: 'P' }))
  graph.addNode(new Belt({ id: 'Q' }))
  graph.addNode(new Belt({ id: 'R' }))
  graph.addNode(new Belt({ id: 'S' }))
  graph.addNode(new Belt({ id: 'T' }))
  graph.addNode(new Belt({ id: 'U' }))
  graph.addNode(new Belt({ id: 'V' }))
  graph.addNode(new Rotator({ id: 'W' }, Rotation.HalfTurn))
  graph.addNode(new Cutter({ id: 'X' }))
  graph.addNode(new Painter({ id: 'Y' }))
  graph.addNode(new Trash({ id: 'Z' }))
  graph.addNode(new Swapper({ id: 'AA' }))
  graph.addNode(new Swapper({ id: 'AB' }))
  graph.addNode(new Stacker({ id: 'AC' }))
  graph.addNode(new Belt({ id: 'AD' }))
  graph.addNode(new Rotator({ id: 'AE' }, Rotation.Anticlockwise))
  graph.addNode(new Belt({ id: 'AF' }))
  graph.addNode(new Belt({ id: 'AG' }))
  graph.addNode(new Belt({ id: 'AH' }))
  graph.addNode(new Belt({ id: 'AI' }))
  graph.addNode(new Belt({ id: 'AJ' }))
  graph.addNode(new Belt({ id: 'AK' }))
  graph.addNode(new Belt({ id: 'AL' }))
  graph.addNode(new Belt({ id: 'AM' }))
  graph.addNode(new Belt({ id: 'AN' }))
  graph.addNode(new Belt({ id: 'AO' }))
  graph.addNode(new Belt({ id: 'AP' }))
  graph.addNode(new Belt({ id: 'AQ' }))
  graph.addNode(new Belt({ id: 'AR' }))
  graph.addNode(new Belt({ id: 'AS' }))
  graph.addNode(new Trash({ id: 'end' }))

  graph.addEdge('shx', 'A', 'shape')
  graph.addEdge('A', 'B', 'shape')
  graph.addEdge('B', 'W', 'shape')
  graph.addEdge('B', 'C', 'shape')
  graph.addEdge('C', 'D', 'shape')
  graph.addEdge('D', 'X', 'shape')
  graph.addEdge('D', 'E', 'shape')
  graph.addEdge('E', 'F', 'shape')
  graph.addEdge('F', 'G', 'shape')
  graph.addEdge('G', 'Y', 'shape')
  graph.addEdge('G', 'H', 'shape')
  graph.addEdge('H', 'I', 'shape')
  graph.addEdge('I', 'J', 'shape')
  graph.addEdge('J', 'Z', 'shape')
  graph.addEdge('J', 'K', 'shape')
  graph.addEdge('K', 'L', 'shape')
  graph.addEdge('L', 'AA', 'shape', 0)
  graph.addEdge('L', 'M', 'shape')
  graph.addEdge('M', 'AA', 'shape', 1)
  graph.addEdge('M', 'N', 'shape')
  graph.addEdge('N', 'O', 'shape')
  graph.addEdge('O', 'AB', 'shape', 0)
  graph.addEdge('O', 'Q', 'shape')
  graph.addEdge('Q', 'R', 'shape')
  graph.addEdge('R', 'AC', 'shape')
  graph.addEdge('R', 'S', 'shape')
  graph.addEdge('S', 'AD', 'shape')
  graph.addEdge('AD', 'AC', 'shape')
  graph.addEdge('T', 'U', 'shape')
  graph.addEdge('U', 'V', 'shape')
  graph.addEdge('V', 'P', 'shape')
  graph.addEdge('P', 'AB', 'shape', 1)
  graph.addEdge('W', 'AE', 'shape')
  graph.addEdge('X', 'AF', 'shape', undefined, 1)
  graph.addEdge('Y', 'AH', 'shape')
  graph.addEdge('Z', 'AK', 'shape')
  graph.addEdge('AB', 'AP', 'shape', undefined, 0)
  graph.addEdge('AB', 'AQ', 'shape', undefined, 1)
  graph.addEdge('AC', 'AS', 'shape')
  graph.addEdge('AG', 'AF', 'shape')
  graph.addEdge('AH', 'AG', 'shape')
  graph.addEdge('AI', 'AH', 'shape')
  graph.addEdge('AJ', 'AI', 'shape')
  graph.addEdge('AK', 'AJ', 'shape')
  graph.addEdge('AL', 'AK', 'shape')
  graph.addEdge('AM', 'AL', 'shape')
  graph.addEdge('AN', 'AM', 'shape')
  graph.addEdge('AO', 'AN', 'shape')
  graph.addEdge('AP', 'AO', 'shape')
  graph.addEdge('AQ', 'AP', 'shape')
  graph.addEdge('AR', 'AQ', 'shape')
  graph.addEdge('AS', 'AR', 'shape')
  graph.addEdge('AF', 'end', 'shape')

  return graph
}

export default {
  swapperSameIO,
  swapperSameISharedO,
  swapperSharedISameO,
  swapperSameIMixedO,
  swapperMixedISameO,
  beltRedundantSplit,
  beltMerge,
  beltBalancer,
  parallelCutter,
  paralelStacker,
  mixerAndPainter,
  pipeSpaghetti,
  deadEnds,
}